### ISSUE TITLE
Failed to download module

### ISSUE THREAD

**Issue by sthamma** [terraform-google-modules/terraform-google-iam#116]
Hi,

I have a module where I am using 'projects_iam'

`module "projects_iam_bindings" {
  source   = "terraform-google-modules/iam/google//modules/projects_iam"
  version  = "~> 6.3"
  mode     = "additive"
  projects = var.projects
  bindings = var.bindings
}`

It worked fine in one instance. I now moved to a new instance , terraform is now giving 'Failed to download module' issue.

Error: Failed to download module

`Could not download module "projects_iam_bindings"
(../modules/iam/project-bindings/main.tf:8) source code from
"git::https://github.com/terraform-google-modules/terraform-google-iam?ref=v6.3.1":
error downloading
'https://github.com/terraform-google-modules/terraform-google-iam?ref=v6.3.1':
/usr/bin/git exited with 1: error: pathspec 'v6.3.1' did not match any file(s)
known to git.`

Can someone please let me know , what the problem is ?

Thanks.

**Comment by morgante** [comment]
You might just want to try deleting the `.terraform` diectory and running `terraform init` again (possibly a few times), seems like this is either a transient error with GitHub or the Terraform module registry.

It's not related to our module because v6.3.1 is clearly available: https://github.com/terraform-google-modules/terraform-google-iam/tree/v6.3.1

**Comment by sthamma** [comment]
Removing .terraform helped. Thank you for the quick response.
