### ISSUE TITLE
Add support for Terraform v0.12

### ISSUE THREAD

**Issue by aaron-lane** [terraform-google-modules/terraform-google-iam#20]

**Comment by jeffmccune** [comment]
Gary and I are working on this.

Acceptance Criteria:

 * [ ] CI passes in the aaron-lane-0.12 release branch PR.
 * [ ] README includes note about 0.12 support
 * [ ] README includes last release supporting 0.11
 * [ ] CHANGELOG staged and ready to release
 * [ ] Modules and providers pinned to appropriate versions for 0.12.

**Comment by jeffmccune** [comment]
IAM Pipeline PR is at: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/209

**Comment by jeffmccune** [comment]
@aaron-lane @Jberlinsky Here's where we left off with the IAM module and CI:

[Fixtures](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/232) and the [pipeline](https://concourse.infra.cft.tips/teams/cft/pipelines/terraform-google-iam) have been created, but are still in flux as we work through test failures.

 * The pipeline running in concourse is defined in https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/232 commit bc4c440
 * The fixtures created in GCP reflect the same commit

We're making minimal changes to get the tests working in #34

Next Steps:

 * [ ] Override Org Policy in the iam fixture folder to get past [Error creating Topic ...  due to an organization policy](https://concourse.infra.cft.tips/teams/cft/pipelines/terraform-google-iam/jobs/integration-tests/builds/11)
 * Continue iterating by pushing commits to a pull request of this repository and observing the Concourse pipeline.

**Comment by jeffmccune** [comment]
* PR #34 is still a WIP to resolve the failures.
* PR [232](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/232/files) may be merged now, the pipeline definition and fixtures reliably get to the test verification phase. 

Next Steps:

 * Resolve test failures ([20](https://concourse.infra.cft.tips/teams/cft/pipelines/terraform-google-iam/jobs/integration-tests/builds/20)
 * Profile Summary: 12 successful controls, 4 control failures, 0 controls skipped
 * Test Summary: 36 successful, 12 failures, 0 skipped
 * Continue iterating by pushing commits to a pull request of this repository and observing the Concourse pipeline.

**Comment by jeffmccune** [comment]
Left off looking into the first kitchen verify failing after `terraform output`.  See [build 24](https://concourse.infra.cft.tips/teams/cft/pipelines/terraform-google-iam/jobs/integration-tests/builds/24).  One new output was added, which may be related to the issue.

```
+ kitchen verify ''
-----> Starting Kitchen (v1.24.0)
-----> Setting up <full-local>...
       Finished setting up <full-local> (0m0.00s).
-----> Verifying <full-local>...
$$$$$$ Running command `terraform workspace select kitchen-terraform-full-local` in directory /tmp/build/f541ec31/terraform-google-iam/test/fixtures/full
$$$$$$ Running command `terraform output -json` in directory /tmp/build/f541ec31/terraform-google-iam/test/fixtures/full
full: Verifying
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Verify failed on instance <full-local>.  Please see .kitchen/logs/full-local.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

+ finish
+ local rv=20
+ echo 'BEGIN: finish() trap handler'
```

**Comment by jeffmccune** [comment]
From the kitchen.log

```
E, [2019-07-15T16:24:43.887402 #1329] ERROR -- Kitchen: ---Nested Exception---
E, [2019-07-15T16:24:43.887419 #1329] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2019-07-15T16:24:43.887434 #1329] ERROR -- Kitchen: Message: full: Profile 'full' does not have an input with name 'fixture_project_id'
E, [2019-07-15T16:24:43.887459 #1329] ERROR -- Kitchen: ----------------------
```

**Comment by jeffmccune** [comment]
@aaron-lane This is ready for review and release, please see the checklist in the description of this issue for links to all the changes and commentary.

**Comment by morgante** [comment]
@aaron-lane Can we release this?

**Comment by aaron-lane** [comment]
Yes, it was released several days ago.
